### ISSUE TITLE
Consider making AsciiDocElement a functional interface

### ISSUE THREAD

**Issue by nils-christian** [archifacts/archifacts#61]
Currently the interface _AsciiDocElement_ has a single method, allowing to do something like the following:
```
final AsciiDoc asciiDoc = new AsciiDoc( );
asciiDoc.addDocElement( ( ) -> "= Some header");
```
In order to make sure that code like this remains compatible, we should consider making _AsciiDocElement_ a functional interface.

**Comment by OLibutzki** [comment]
Agreed
