### ISSUE TITLE
Equals on descriptor types and roles leads to unexpected behaviour

### ISSUE THREAD

**Issue by nils-christian** [archifacts/archifacts#62]
Currently the types/roles of building blocks, containers, and relationships perform an equals based on equality of the String. Although this surely is a valid approach, it leads to weird behaviour in case that two descriptors have types with the same names.

Consider for instance the relationship descriptors for Axon, which have types with the same name (and are wrongly even of the same instance). Now it is not possible to query the _Application_ only for the _QueryHandlerDescriptor_, as all relationships are found.

I suggest the following:
* Perform the equality check of types/roles based on reference equality.
* Make sure that all our own descriptors have an unique instance (per class).

**Comment by OLibutzki** [comment]
I agree on this.

We should consider _BuildingBlockType_, _ArtifactContainerType_ and _ArtifactRelationshipRole_ to be equal iff they are the very same instance.

Clients can easily access those instances by calling `.BuildingBlockDescriptor.type()`, `ArtifactContainerDescriptor.type()` or `ArtifactRelationshipDescriptor.role()`.

Descriptors are forced not to build a new role/type instance on each method call, but to have a 1:1 relationship between descriptor instance and type/role instance. Anyway, I'm sure all the descriptors we currently have don't violate this contract.
