### ISSUE TITLE
Extend ArtifactContainer with methods to query for relationships

### ISSUE THREAD

**Issue by nils-christian** [archifacts/archifacts#63]
While the _application_ class has a method to query relationships of a certain role, the _ArtifactContainer_ does not. It would be nice if one could query the container for incoming/outgoing relationships of a certain role.

**Comment by OLibutzki** [comment]
So you expect _ArtifactContainer_ to implement _HasRelationships_? What's the outcome? Relationships themselves are not part of a container, but the source and target artifacts might have a container.

Do you expect the method to return all relationships whose source and/or target artifact is part of the container?

Another idea:
We can think about some _HasIncomingRelationships_ interface which provides `Set<ArtifactRelationship> getIncomingRelationships()` and `Set<ArtifactRelationship> getIncomingRelationshipsOfRole(ArtifactRelationshipRole)` in analogy to _HasRelationships_. Same applies to _HasOutgoingRelationships_.

These interface can be implemented by _Artifact_ and _ArtifactContainer_.

**Comment by nils-christian** [comment]
Sounds good to me.
