### ISSUE TITLE
Add an AsciiDocElement for tables

### ISSUE THREAD

**Issue by nils-christian** [archifacts/archifacts#64]
While generating an architecture documentation for our application, we noticed that it was often useful to list certain elements in tables. It would be nice if archifacts-asciidoc would provide a simple implementation for a table. I was thinking about an extendable single-column table with a generic and a label extractor function. Another default implementation could extend it and display _Named_ elements. 

```
public class TableDocElement<T> {

  public TableDocElement(final String label, final Iterable<T> elements, final Function<T, String> labelExtractor) {...}
  
}

public final class NamedDocElement<T extends Named> extends TableDocElement<T> {
  ...  
}
```

We should of course extend the example with such a table.

**Comment by OLibutzki** [comment]
Don't you  think that a single-column table is a bit limited?

What about having some kind of builder to descirbe the table, for instance:
```
TableDocElement.for(elements).
 .column("Column 1", MyElement::getValue1)
 .column("Column 2", MyElement::getValue2)
 .build();
```

First of all the pass the `Iterable<T>` and then you can define column: `column(String header, Function<T, String> labelExtractor`.

The _Named_ interface is something I rather would like to keep internal... so I'm thinking about reducing its visibility to _package private_.

**Comment by nils-christian** [comment]
Sounds good. I will implement a first attempt for such a table.
