### ISSUE TITLE
Inconsistent behaviour of query/getter methods regarding immutability

### ISSUE THREAD

**Issue by nils-christian** [archifacts/archifacts#72]
I noticed that some of the query/getter methods in archifacts return a immutable collections while other do not. This leads to an inconsistent behaviour of the API.

I can't do this: 
```application.getArtifacts().add( ...)```
But I can do this: 
```application.getArtifactsOfType(...).add(...)```
I can't do this: 
```application.getRelationships().add(...);```
But I can do this:
```application.getBuildingBlocks().add(...);```

In the very least we should document this behaviour. It would probably be better if all those methods would return an immutable collection.

**Comment by OLibutzki** [comment]
The application model cannot be immutable because of its bidirectional relationships.

Nevertheless, it should be immutable effectively, meaning that all the getters return immutable collections or types with package private modification methods.
