### ISSUE TITLE
TableDocElement shouldn't render anything if the items are empty

### ISSUE THREAD

**Issue by nils-christian** [archifacts/archifacts#75]
If the items of the TableDocElement are empty, the table shouldn't render anything. Alternatively, it should be configurable whether an empty table should still be rendered (default: false).

**Comment by OLibutzki** [comment]
Not sure about this issue. In my opinion it's the responsibility of the client if the table should be rendered or not. If there are no elements to be displayed it's possible to omit the creation of `TableDocElement` entirely.

I can think of cases when you want to show explicitly that there are no elements in a certain table.
Yes, we can make it configurable, but do we win anything compared to an `if` in the client's code?

**Comment by nils-christian** [comment]
I would say that it would be just a convenient function, but I agree that such a behaviour is not available for component in other areas (web or desktop frontends). Therefore I withdraw this issue.
